title:            For i in Espresso
description:      Sagar's Musings

# Your site's domain goes here. Leave localhost server or blank when working locally.
url:              http://sagarjauhari.github.io
#url:              http://localhost:4000
disqus_shortname: sagarjauhari

# Owner/author information
owner:
  name:           Sagar Jauhari
  avatar:         bio-photo.jpg
  bio:            "Programmer | Dreamer | Creator"
  #email:          your@email.com
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  twitter:        sagarjauhari
  facebook:       sagarjauhari
  github:         sagarjauhari
  stackoverflow:
  linkedin:
  instagram:      sagarjauhari
  lastfm:
  tumblr:
  pinterest:      sagarjauhari
  foursquare:     sagarjauhari
  steam:
  dribbble:
  # For Google Authorship https://plus.google.com/authorship
  google_plus: sagarjauhari

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about/
  - title: Posts
    url: /posts/
  - title: BCIpy
    url: http://bcipy.org
    external: true
  # - title: Food
  #   url: /food/
  # - title: Music
  #   url: /music/
  - title: Projects
    url: /projects/

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      true
pygments:    true
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]

# Projects (till I move them to a new file)
projects:
  - title: Anomaly detection in time series graphs
    img_url: /images/proj_anomaly.png
    github_repo: graph_anomaly_detect
    description: Anomaly detection in time series graphs 
#  - title: 
#    img_url:
#    website: 
#    github_repo:
#    nbviewer:
#    description:
